<script src="<?= TEMPLATE ?>admin/js/simple-datatables.min.js"></script>
<script src="<?= TEMPLATE ?>admin/js/quill.min.js"></script>
<!--<script src="--><?//= TEMPLATE ?><!--admin/js/quill-image-drop-and-paste.min.js"></script>-->
<script src="<?= TEMPLATE ?>admin/js/image-resize.min.js"></script>
<script src="<?= TEMPLATE ?>admin/js/quill.imageUploader.min.js"></script>
<script src="<?= TEMPLATE ?>admin/js/dropzone.min.js"></script>
<!--<script src="--><?//= TEMPLATE ?><!--admin/js/selectr.min.js"></script>-->
<script src="<?= TEMPLATE ?>admin/js/tom-select.complete.min.js"></script>
<script src="<?= TEMPLATE ?>admin/js/app.js"></script>
<script src="<?= TEMPLATE ?>admin/js/custom.js"></script>
